// ─── Colour Palette ───────────────────────────────────────────────────────────
export const COLORS = [
  "#4f46e5", "#7c3aed", "#0ea5e9", "#0d9488", "#059669",
  "#16a34a", "#ca8a04", "#ea580c", "#dc2626", "#be185d",
  "#9333ea", "#0891b2", "#1d4ed8", "#1e3a8a", "#134e4a",
  "#111827", "#374151", "#6d28d9", "#b91c1c", "#92400e",
];

// ─── All Templates ────────────────────────────────────────────────────────────
export const TEMPLATES = [
  { id: 1,   name: "Traditional Classic",   type: "Modern",    badge: "popular", accent: "#1e3a8a", layout: "sidebar"    },
  { id: 2,   name: "Modern Blue Sidebar",   type: "Modern",    badge: "popular", accent: "#2563eb", layout: "sidebar"    },
  { id: 3,   name: "Clean Split",           type: "Modern",    badge: "",        accent: "#0f766e", layout: "sidebar"    },
  { id: 4,   name: "Slate Pro",             type: "Modern",    badge: "new",     accent: "#334155", layout: "top"        },
  { id: 5,   name: "Navy Executive",        type: "Modern",    badge: "",        accent: "#1e40af", layout: "sidebar"    },
  { id: 6,   name: "Teal Flow",             type: "Modern",    badge: "",        accent: "#0d9488", layout: "top"        },
  { id: 7,   name: "Indigo Wave",           type: "Modern",    badge: "",        accent: "#4f46e5", layout: "top"        },
  { id: 8,   name: "Midnight",              type: "Modern",    badge: "",        accent: "#1e3a8a", layout: "top"        },
  { id: 9,   name: "Purple Wave",           type: "Modern",    badge: "new",     accent: "#7c3aed", layout: "top"        },
  { id: 10,  name: "Ocean Depth",           type: "Modern",    badge: "",        accent: "#0369a1", layout: "sidebar"    },
  { id: 11,  name: "Simple White",          type: "Minimal",   badge: "popular", accent: "#374151", layout: "minimal"    },
  { id: 12,  name: "Minimal ATS",           type: "ATS",       badge: "popular", accent: "#111827", layout: "minimal"    },
  { id: 13,  name: "Pure White",            type: "Minimal",   badge: "",        accent: "#6b7280", layout: "minimal"    },
  { id: 14,  name: "Subtle Gray",           type: "Minimal",   badge: "",        accent: "#374151", layout: "minimal"    },
  { id: 15,  name: "Clean Lines",           type: "Minimal",   badge: "",        accent: "#111827", layout: "minimal"    },
  { id: 16,  name: "ATS One Column",        type: "ATS",       badge: "",        accent: "#1f2937", layout: "minimal"    },
  { id: 17,  name: "Prime ATS",             type: "ATS",       badge: "new",     accent: "#374151", layout: "minimal"    },
  { id: 18,  name: "Recruiter Ready",       type: "ATS",       badge: "",        accent: "#0f172a", layout: "minimal"    },
  { id: 19,  name: "No Frills",             type: "Minimal",   badge: "",        accent: "#4b5563", layout: "minimal"    },
  { id: 20,  name: "Clean ATS Pro",         type: "ATS",       badge: "",        accent: "#1e293b", layout: "minimal"    },
  { id: 21,  name: "Color Blocks",          type: "Creative",  badge: "popular", accent: "#be185d", layout: "top"        },
  { id: 22,  name: "Designer Bold",         type: "Designer",  badge: "",        accent: "#7c3aed", layout: "top"        },
  { id: 23,  name: "Gradient Burst",        type: "Creative",  badge: "new",     accent: "#dc2626", layout: "top"        },
  { id: 24,  name: "Neon Minimal",          type: "Designer",  badge: "",        accent: "#059669", layout: "top"        },
  { id: 25,  name: "Art Director",          type: "Creative",  badge: "",        accent: "#d97706", layout: "top"        },
  { id: 26,  name: "Portfolio Bold",        type: "Designer",  badge: "",        accent: "#9333ea", layout: "sidebar"    },
  { id: 27,  name: "Vivid Orange",          type: "Creative",  badge: "",        accent: "#ea580c", layout: "top"        },
  { id: 28,  name: "Pink Studio",           type: "Creative",  badge: "new",     accent: "#db2777", layout: "top"        },
  { id: 29,  name: "Lime Fresh",            type: "Designer",  badge: "",        accent: "#65a30d", layout: "top"        },
  { id: 30,  name: "Deep Red",              type: "Creative",  badge: "",        accent: "#b91c1c", layout: "top"        },
  { id: 31,  name: "Corporate Classic",     type: "Corporate", badge: "popular", accent: "#1d4ed8", layout: "corporate"  },
  { id: 32,  name: "Executive Clean",       type: "Executive", badge: "popular", accent: "#1e293b", layout: "corporate"  },
  { id: 33,  name: "Manager Pro",           type: "Corporate", badge: "",        accent: "#1e3a8a", layout: "corporate"  },
  { id: 34,  name: "Senior Leader",         type: "Executive", badge: "new",     accent: "#0f172a", layout: "corporate"  },
  { id: 35,  name: "C-Suite",               type: "Executive", badge: "",        accent: "#111827", layout: "corporate"  },
  { id: 36,  name: "Director Level",        type: "Corporate", badge: "",        accent: "#1e40af", layout: "corporate"  },
  { id: 37,  name: "VP Profile",            type: "Executive", badge: "",        accent: "#334155", layout: "corporate"  },
  { id: 38,  name: "Board Ready",           type: "Executive", badge: "",        accent: "#0c4a6e", layout: "corporate"  },
  { id: 39,  name: "Consultant",            type: "Corporate", badge: "",        accent: "#1d4ed8", layout: "corporate"  },
  { id: 40,  name: "Finance Pro",           type: "Corporate", badge: "",        accent: "#15803d", layout: "corporate"  },
  { id: 41,  name: "Researcher CV",         type: "Academic",  badge: "popular", accent: "#6d28d9", layout: "minimal"    },
  { id: 42,  name: "PhD Template",          type: "Academic",  badge: "",        accent: "#1e3a8a", layout: "minimal"    },
  { id: 43,  name: "Academic Clean",        type: "Academic",  badge: "",        accent: "#0f766e", layout: "minimal"    },
  { id: 44,  name: "Faculty CV",            type: "Academic",  badge: "new",     accent: "#7c3aed", layout: "minimal"    },
  { id: 45,  name: "PostDoc Ready",         type: "Academic",  badge: "",        accent: "#1d4ed8", layout: "minimal"    },
  { id: 46,  name: "Dev Stack",             type: "Tech",      badge: "popular", accent: "#0f172a", layout: "sidebar"    },
  { id: 47,  name: "GitHub Style",          type: "Tech",      badge: "",        accent: "#1f2937", layout: "minimal"    },
  { id: 48,  name: "Full Stack",            type: "Tech",      badge: "new",     accent: "#4f46e5", layout: "sidebar"    },
  { id: 49,  name: "Engineering CV",        type: "Tech",      badge: "",        accent: "#0369a1", layout: "sidebar"    },
  { id: 50,  name: "Data Scientist",        type: "Tech",      badge: "",        accent: "#0d9488", layout: "top"        },
  { id: 51,  name: "AI Engineer",           type: "Tech",      badge: "new",     accent: "#6d28d9", layout: "top"        },
  { id: 52,  name: "Backend Dev",           type: "Tech",      badge: "",        accent: "#374151", layout: "minimal"    },
  { id: 53,  name: "SRE Profile",           type: "Tech",      badge: "",        accent: "#1e293b", layout: "corporate"  },
  { id: 54,  name: "Cloud Architect",       type: "Tech",      badge: "",        accent: "#0e7490", layout: "sidebar"    },
  { id: 55,  name: "Cybersecurity",         type: "Tech",      badge: "",        accent: "#7c3aed", layout: "minimal"    },
  { id: 56,  name: "Entry Level",           type: "Modern",    badge: "",        accent: "#2563eb", layout: "top"        },
  { id: 57,  name: "Fresh Graduate",        type: "Minimal",   badge: "",        accent: "#16a34a", layout: "minimal"    },
  { id: 58,  name: "Internship",            type: "Minimal",   badge: "",        accent: "#0891b2", layout: "minimal"    },
  { id: 59,  name: "Student CV",            type: "Academic",  badge: "",        accent: "#7c3aed", layout: "minimal"    },
  { id: 60,  name: "Career Switch",         type: "Modern",    badge: "",        accent: "#ea580c", layout: "top"        },
  { id: 61,  name: "Sales Leader",          type: "Corporate", badge: "",        accent: "#15803d", layout: "corporate"  },
  { id: 62,  name: "HR Manager",            type: "Corporate", badge: "",        accent: "#be185d", layout: "corporate"  },
  { id: 63,  name: "Marketing Pro",         type: "Creative",  badge: "",        accent: "#db2777", layout: "top"        },
  { id: 64,  name: "Brand Manager",         type: "Creative",  badge: "",        accent: "#9333ea", layout: "top"        },
  { id: 65,  name: "UX Designer",           type: "Designer",  badge: "popular", accent: "#0891b2", layout: "sidebar"    },
  { id: 66,  name: "Product Manager",       type: "Corporate", badge: "new",     accent: "#4f46e5", layout: "corporate"  },
  { id: 67,  name: "Operations",            type: "Corporate", badge: "",        accent: "#334155", layout: "corporate"  },
  { id: 68,  name: "Legal CV",              type: "Corporate", badge: "",        accent: "#1e293b", layout: "minimal"    },
  { id: 69,  name: "Medical CV",            type: "Academic",  badge: "",        accent: "#0f766e", layout: "minimal"    },
  { id: 70,  name: "Teacher CV",            type: "Academic",  badge: "",        accent: "#7c3aed", layout: "minimal"    },
  { id: 71,  name: "Dev Portfolio",         type: "Designer",  badge: "",        accent: "#6d28d9", layout: "sidebar"    },
  { id: 72,  name: "Photographer",          type: "Designer",  badge: "",        accent: "#111827", layout: "sidebar"    },
  { id: 73,  name: "Journalist",            type: "Minimal",   badge: "",        accent: "#dc2626", layout: "minimal"    },
  { id: 74,  name: "Finance Analyst",       type: "Corporate", badge: "",        accent: "#1d4ed8", layout: "corporate"  },
  { id: 75,  name: "Investment Pro",        type: "Executive", badge: "",        accent: "#1e3a8a", layout: "corporate"  },
  { id: 76,  name: "Startup Founder",       type: "Modern",    badge: "",        accent: "#ea580c", layout: "top"        },
  { id: 77,  name: "Entrepreneur",          type: "Creative",  badge: "",        accent: "#d97706", layout: "top"        },
  { id: 78,  name: "Freelancer",            type: "Minimal",   badge: "",        accent: "#0891b2", layout: "minimal"    },
  { id: 79,  name: "Remote Worker",         type: "Modern",    badge: "new",     accent: "#6d28d9", layout: "top"        },
  { id: 80,  name: "Consultant CV",         type: "Corporate", badge: "",        accent: "#1e40af", layout: "corporate"  },
  { id: 81,  name: "Classic Serif",         type: "Minimal",   badge: "",        accent: "#292524", layout: "minimal"    },
  { id: 82,  name: "Timeline Resume",       type: "Modern",    badge: "new",     accent: "#0369a1", layout: "top"        },
  { id: 83,  name: "Infographic CV",        type: "Creative",  badge: "",        accent: "#7c3aed", layout: "top"        },
  { id: 84,  name: "Two Page Pro",          type: "Corporate", badge: "",        accent: "#1e293b", layout: "corporate"  },
  { id: 85,  name: "Functional CV",         type: "ATS",       badge: "",        accent: "#374151", layout: "minimal"    },
  { id: 86,  name: "Skills First",          type: "ATS",       badge: "",        accent: "#1e3a8a", layout: "minimal"    },
  { id: 87,  name: "Monochrome",            type: "Minimal",   badge: "",        accent: "#111827", layout: "minimal"    },
  { id: 88,  name: "Bold Statement",        type: "Creative",  badge: "new",     accent: "#b91c1c", layout: "top"        },
  { id: 89,  name: "Geometric",             type: "Designer",  badge: "",        accent: "#0f766e", layout: "top"        },
  { id: 90,  name: "Spectrum",              type: "Creative",  badge: "",        accent: "#7c3aed", layout: "top"        },
  { id: 91,  name: "Executive Brief",       type: "Executive", badge: "",        accent: "#1e293b", layout: "corporate"  },
  { id: 92,  name: "Leadership CV",         type: "Executive", badge: "",        accent: "#0f172a", layout: "corporate"  },
  { id: 93,  name: "Strategy Lead",         type: "Corporate", badge: "",        accent: "#1d4ed8", layout: "corporate"  },
  { id: 94,  name: "Biotech CV",            type: "Academic",  badge: "",        accent: "#059669", layout: "minimal"    },
  { id: 95,  name: "Pastel Soft",           type: "Modern",    badge: "",        accent: "#a78bfa", layout: "top"        },
  { id: 96,  name: "Scrum Master",          type: "Tech",      badge: "",        accent: "#0f766e", layout: "top"        },
  { id: 97,  name: "Nurse Profile",         type: "Academic",  badge: "",        accent: "#0891b2", layout: "minimal"    },
  { id: 98,  name: "Accountant",            type: "Corporate", badge: "",        accent: "#15803d", layout: "corporate"  },
  { id: 99,  name: "Banker",                type: "Executive", badge: "",        accent: "#0c4a6e", layout: "corporate"  },
  { id: 100, name: "COO Profile",           type: "Executive", badge: "",        accent: "#111827", layout: "corporate"  },
  { id: 101, name: "ML Engineer",           type: "Tech",      badge: "new",     accent: "#4f46e5", layout: "sidebar"    },
  { id: 102, name: "DevOps Pro",            type: "Tech",      badge: "",        accent: "#0d9488", layout: "top"        },
  { id: 103, name: "Blockchain Dev",        type: "Tech",      badge: "",        accent: "#1f2937", layout: "minimal"    },
  { id: 104, name: "Open Source CV",        type: "Tech",      badge: "",        accent: "#374151", layout: "minimal"    },
  { id: 105, name: "COO Profile II",        type: "Executive", badge: "",        accent: "#0f172a", layout: "corporate"  },
  { id: 106, name: "Classic Split Pro",     type: "Modern",    badge: "new",     accent: "#1e293b", layout: "resumeio"         },
  { id: 107, name: "Ocean Sidebar Expert",  type: "Corporate", badge: "new",     accent: "#0f766e", layout: "resumeioSidebar"  },
  { id: 108, name: "Mono Detail Grid",      type: "ATS",       badge: "",        accent: "#334155", layout: "resumeioBoxed"    },
  { id: 109, name: "Navy Executive Panel",  type: "Executive", badge: "new",     accent: "#0f172a", layout: "resumeioDark"     },
  { id: 110, name: "Soft Minimal Split",    type: "Minimal",   badge: "",        accent: "#475569", layout: "resumeioClean"    },
  { id: 111, name: "Green Profile Line",    type: "Modern",    badge: "",        accent: "#0f766e", layout: "resumeioSidebar"  },
  { id: 112, name: "Melanie Blue Panel",    type: "Corporate", badge: "new",     accent: "#3f6fc4", layout: "coolBluePanel"   },
  { id: 113, name: "Jamie Noir Hero",       type: "Modern",    badge: "new",     accent: "#111827", layout: "noirTop"         },
  { id: 114, name: "Royal Curve",           type: "Designer",  badge: "new",     accent: "#4c2f8f", layout: "purpleCurve"     },
  { id: 115, name: "Mint Geometry",         type: "Designer",  badge: "new",     accent: "#22c7a0", layout: "mintGeo"         },
  { id: 116, name: "Modern Popular Mono",   type: "Modern",    badge: "new",     accent: "#111827", layout: "modernPopular"   },
  { id: 117, name: "Modern Popular Cyan",   type: "Modern",    badge: "",        accent: "#0ea5e9", layout: "modernPopular"   },
  { id: 118, name: "Brown Graphic Pro",     type: "Designer",  badge: "new",     accent: "#b96434", layout: "brownClassic"    },
  { id: 119, name: "Jamie Noir Exact",      type: "Modern",    badge: "new",     accent: "#111827", layout: "noirHeroExact"   },
  { id: 120, name: "Modern Clean Strip",    type: "Modern",    badge: "new",     accent: "#111827", layout: "modernCleanStrip"},
  { id: 121, name: "Mono Sidebar Classic",  type: "Minimal",   badge: "new",     accent: "#6b7280", layout: "monoSidebarClassic"},
  { id: 122, name: "Teal Executive Side",   type: "Corporate", badge: "new",     accent: "#0b5568", layout: "tealExecutiveSide"},
  { id: 123, name: "Choco Profile Art",     type: "Designer",  badge: "new",     accent: "#7c3f2b", layout: "chocoProfileArt"},
  { id: 124, name: "Teal Data Grid",        type: "Modern",    badge: "new",     accent: "#74a89f", layout: "tealDataGrid"},
];

// ─── Gallery category groupings ───────────────────────────────────────────────
export const CATEGORIES = {
  "Popular Picks":         [1, 2, 12, 21, 31, 32, 46, 65, 106, 119],
  "Modern & Stylish":      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 56, 60, 76, 79, 82, 95, 106, 111, 113, 116, 117, 119, 120, 122, 124],
  "Minimal & Clean":       [11, 13, 14, 15, 19, 57, 58, 73, 78, 81, 87, 108, 110, 121],
  "ATS Friendly":          [12, 16, 17, 18, 20, 85, 86, 108, 110],
  "Creative & Bold":       [21, 22, 23, 24, 25, 27, 28, 29, 30, 63, 64, 77, 83, 88, 89, 90, 114, 115, 118, 123],
  "Corporate & Executive": [31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 61, 62, 66, 67, 68, 74, 75, 80, 84, 91, 92, 93, 98, 99, 100, 107, 109, 112, 122],
  "Tech & Engineering":    [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 96, 101, 102, 103, 104],
  "Academic & Research":   [41, 42, 43, 44, 45, 59, 69, 70, 94, 97],
  "Designer Portfolio":    [22, 24, 26, 29, 65, 71, 72, 89, 106, 107, 108, 109, 110, 111, 114, 115, 118, 121, 123],
};

export const FILTER_TYPES = ["All", "Modern", "Minimal", "ATS", "Creative", "Corporate", "Executive", "Tech", "Academic", "Designer"];

export const FONT_OPTIONS = [
  { label: "Modern",   value: "'Segoe UI', sans-serif" },
  { label: "Classic",  value: "Georgia, serif" },
  { label: "Mono",     value: "'Courier New', monospace" },
  { label: "Rounded",  value: "'Trebuchet MS', sans-serif" },
  { label: "Elegant",  value: "Garamond, serif" },
];

export const DEFAULT_FORM = {
  fname: "John", lname: "Doe",
  title: "Software Engineer",
  email: "john@email.com",
  phone: "+1 234 567 890",
  linkedin: "linkedin.com/in/johndoe",
  github: "github.com/johndoe",
  twitter: "",
  portfolio: "",
  summary: "Experienced developer with 5+ years building scalable web applications.",
  experience: [
    { id: "1", jobtitle: "Senior Developer", company: "Acme Corp", jobstart: "2021", jobend: "Present", jobdesc: "Led development of core product features serving 1M+ users." }
  ],
  education: [
    { id: "1", degree: "B.S. Computer Science", school: "State University", gradyear: "2020", gpa: "3.8" }
  ],
  skills: "JavaScript, React, Node.js, Python",
  languages: [
    { id: "1", language: "English", langLevel: "Native" }
  ],
  projects: [],
  certifications: [],
  interests: "Photography, Open Source, Hiking",
};